name: Publish NuGet.org

on:
  push:
    branches: [ master ]

jobs:
  build:
    permissions:
      contents: read
      id-token: write  # enable GitHub OIDC token issuance for this job
    runs-on: windows-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Use .NET 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Update the Version Number
        run: |
          (Get-Content Notification.Wpf\Notification.Wpf.csproj) -Replace '<Version>*.{7}</Version>', '<Version>${{ vars.STABLEVERSION }}.0</Version>' | Set-Content Notification.Wpf\Notification.Wpf.csproj
        
      - name: Building
        run: dotnet build Notification.Wpf\Notification.Wpf.csproj -c Release
        
      - name: Packing
        run: |                    
          dotnet build Notification.Wpf/Notification.Wpf.csproj -c Release
          dotnet pack Notification.Wpf/Notification.Wpf.csproj -c Release

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: push to NuGet
        shell: pwsh
        run: |
          dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json --api-key "${{ steps.login.outputs.NUGET_API_KEY }}"
          dotnet nuget push "**/*.snupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json --api-key "${{ steps.login.outputs.NUGET_API_KEY }}"